key:
  ENDPOINT_GETUSERDETAILS: getUserDetails?username=
  ENDPOINT_SENDMAIL: sendMail
  MAIL_FROM: atultingre.test@gmail.com
  MAIL_PASS: Amazon@1122
  MAIL_TO: skncoeavinash@gmail.com
  REST_URL: http://localhost:7777/ShippingApplication/

server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
