API:
  REST_URL: http://localhost:7777/ShippingApplication/
  ENDPOINT_GETUSERDETAILS: getUserDetails?username=
  ENDPOINT_SENDMAIL: sendMail
  ENDPOINT_CREATEORDER: createOrder
  ENDPOINT_GETALLORDERS: getAllOrders
  ENDPOINT_UPDATEORDER: updateOrder
  ENDPOINT_UPDATEBATCHORDERS: updateBatchOrders
  ENDPOINT_DELETEORDER: deleteOrder?orderid=
  ENDPOINT_GETORDERBYID: getOrderDetails?orderid=
  OUTPUT_FILE_PATH: C:\Work\Projects\Hotfix Viewer Spring\Testexcelfile.xlsx
  
server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
