API:
  REST_URL: http://localhost:7777/ShippingApplication/
  ENDPOINT_GETUSERDETAILS: getUserDetails?username=
  ENDPOINT_SENDMAIL: sendMail
  
server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
